# -*- coding: utf-8 -*-
"""Hangman_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPMni5kwj34Xzc8I7Y1dqKH7QqAw2lN7
"""

import random

words = ["python", "program", "computer", "smartphone", "student"]

word = random.choice(words)
guessed = ["_"] * len(word)

attempts = 7

print("Welcome to Hangman!")

while attempts > 0 and "_" in guessed:
    print("\nWord:", " ".join(guessed))
    guess = input("Enter a letter: ").lower()

    if guess in word:
        for i in range(len(word)):
            if word[i] == guess:
                guessed[i] = guess
        print("Correct!")
    else:
        attempts -= 1
        print("Wrong! Attempts left:", attempts)

if "_" not in guessed:
    print("\nCongratulations! You guessed:", word)
else:
    print("\nGame Over! The word was:", word)